### ISSUE TITLE
SOURCE_ID and layerId as parameters

### ISSUE THREAD

**Issue by clement-igonet** [indoorequal/mapbox-gl-indoorequal#10]
Enjoying your mapbox indoor plugin using an alternative data sources,  it would be convenient to define an other possible SOURCE_ID, and also an other possible layerId to parse levels.

Example of use:
```
            const indoorEqual = new IndoorEqual(map,
                {
                    url: 'http://localhost/data/france_mbtiles.json',
                    sourceId: "france",
                    layerId: "osm-indoor",
                    layers: layers
                }
            );
```

F.Y.I., what I do locally in src/index.js:
```
const DEFAULT_SOURCE_ID = 'indoorequal';
const DEFAULT_LAYER_ID = 'osm-indoor'
```
and then in IndoorEqual constructor block:
```
    this.sourceId = opts.sourceId ?? DEFAULT_SOURCE_ID;
    this.layerId = opts.layerId ?? DEFAULT_LAYER_ID;
```
and so on...

**Comment by francois2metz** [comment]
Hi there,

Does it means that your data source is not using the indoorequal vector tile schema?

**Comment by clement-igonet** [comment]
Yes.

**Comment by francois2metz** [comment]
Not sure I should add support for that as the complexity will grow. I may accept a patch if there is enough tests.

**Comment by francois2metz** [comment]
After thinking about it I'm wondering why you need to change the source id?

**Comment by clement-igonet** [comment]
Data I'm using are directly converted from osmtogeojson transformation. It could be used for wide usages.
But I could also set source id in data I manage as current SOURCE_ID constant. You're right.

**Comment by francois2metz** [comment]
Closing as there is no interest to provide a pull request. Reopen it otherwise.
