### ISSUE TITLE
Conspicuous tile boundaries

### ISSUE THREAD

**Issue by FredFronky** [indoorequal/mapbox-gl-indoorequal#16]
Hi there,
I've noticed that there are a few locations that are on tile boundaries which show clear lines on the indoor maps.
An example here: [https://indoorequal.org/#map=17.67/-0.176206/-78.478942](https://indoorequal.org/#map=17.67/-0.176206/-78.478942)
![image](https://user-images.githubusercontent.com/10494105/112933062-a40ded80-9166-11eb-8c7a-d1d53ec66494.png)
and here:
[https://indoorequal.org/#map=17.04/35.712996/139.776567&level=0](https://indoorequal.org/#map=17.04/35.712996/139.776567&level=0)
![image](https://user-images.githubusercontent.com/10494105/112933168-d7e91300-9166-11eb-9909-7cdecae13512.png)

They are more or less obvious at different zoom levels, but are not particularly visually appealing.
Is this due to a limitation of the mapbox platform, or is there something I can do to remedy this?
Thanks

**Comment by francois2metz** [comment]
I saw this change in the openmaptiles-tools repo that may fix it: https://github.com/openmaptiles/openmaptiles-tools/pull/334

**Comment by francois2metz** [comment]
Hi there.

I believe I have fixed the issue by upgrading to openmaptiles-tools 5.3. Fixed in https://github.com/indoorequal/indoorequal/commit/9122de3404c82e863136d750258bbae56893b30c
